version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_backend
    volumes:
      - ./backend:/docker/node/backend
      - ./public:/docker/node/public
    working_dir: /docker/node
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
